version: '3.7'
services:
  web-scraping-project:
    deploy:
      replicas: 1
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    env_file:
    - ./dev.env

    networks:
      - frontend

networks:
  frontend:
    driver: overlay
    external: true
